### ISSUE TITLE
Pod is running but vmi is Scheduled

### ISSUE THREAD

**Issue by newhuangchuan** [k8snetworkplumbingwg/sriov-network-device-plugin#389]
### What happened?
```
uos@uos-PC:~/kubevirt/network$ kubectl  get pod  && kubectl get vmi
NAME                           READY   STATUS    RESTARTS   AGE
testpod1                       1/1     Running   3          163m
testpod2                       1/1     Running   3          162m
virt-launcher-vmi-perf-pr5r2   2/2     Running   0          5m49s

NAME            AGE     PHASE       IP              NODENAME
vmi-perf        5m49s   Scheduled   192.168.0.51    uos-pc
```
### What did you expect to happen?
uos@uos-PC:~/kubevirt/network$ kubectl  get pod  && kubectl get vmi
NAME                           READY   STATUS    RESTARTS   AGE
testpod1                       1/1     Running   3          163m
testpod2                       1/1     Running   3          162m
virt-launcher-vmi-perf-pr5r2   2/2     Running   0          5m49s
NAME            AGE     PHASE       IP              NODENAME
vmi-perf        5m49s   Running  192.168.0.51    uos-pc
### What are the minimal steps needed to reproduce the bug?
2
### Component Versions
Please fill in the below table with the version numbers of components used.

Component | Version|
------------------------------|--------------------|
|SR-IOV Network Device Plugin |<v3.3.1>|
|SR-IOV CNI Plugin            |<v2.6.1>|
|Multus                       |<v3.7.1>|
|Kubernetes                   |<v1.18.5>| 
|OS                           |<Input Version Here>|

### Config Files
Config file locations may be config dependent.
```
uos@uos-PC:~/kubevirt/network$ cat vm.yaml 
---
apiVersion: kubevirt.io/v1alpha3
kind: VirtualMachineInstance
metadata:
  labels:
    special: vmi-perf
  name: vmi-perf
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1
spec:
  domain:
    cpu:
      model: host-passthrough
      sockets: 2
      cores: 1
      threads: 1
      dedicatedCpuPlacement: true
    resources:
      requests:
        memory: "4Gi"
        intel.com/intel_sriov_netdevice: '1'
      limits:
        memory: "4Gi"
        intel.com/intel_sriov_netdevice: '1'
    devices:
      disks:
      - disk:
          bus: virtio
        name: containerdisk
      - disk:
          bus: virtio
        name: cloudinitdisk
      interfaces:
      - masquerade: {}
        name: default
      - name: sriov-net1
        sriov: {}
      rng: {}
    machine:
      type: ""
  networks:
  - name: default
    pod: {}
  - multus:
      networkName: default/sriov-net1
    name: sriov-net1
  terminationGracePeriodSeconds: 0
  volumes:
  - containerDisk:
      image: docker.io/kubevirt/fedora-cloud-container-disk-demo:latest
      imagePullPolicy: Never
    name: containerdisk
  - cloudInitNoCloud:
      userData: |
        #!/bin/bash
        echo "centos" |passwd centos --stdin
        dhclient eth1
    name: cloudinitdisk

```
##### Device pool config file location (Try '/etc/pcidp/config.json')
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [{
                "resourceName": "intel_sriov_netdevice",
                "selectors": {
                    "vendors": ["8086"],
                    "devices": ["37cd","154c", "10ed"],
                    "drivers": ["i40evf", "iavf", "ixgbevf"]
                }
            }
        ]
    }
```
##### Kubernetes deployment type ( Bare Metal, Kubeadm etc.)
kubeadm
##### SR-IOV Network Custom Resource Definition
```
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net1
  annotations:
    k8s.v1.cni.cncf.io/resourceName: intel.com/intel_sriov_netdevice
spec:
  config: '{
  "type": "sriov",
  "cniVersion": "0.3.1",
  "name": "sriov-network",
  "ipam": {
    "type": "host-local",
    "subnet": "10.56.217.0/24",
    "routes": [{
      "dst": "0.0.0.0/0"
    }],
    "gateway": "10.56.217.1"
  }
}'
```
### Logs
```
 $ kubectl  describe vmi vmi-perf

Name:         vmi-perf
Namespace:    default
Labels:       kubevirt.io/nodeName=uos-pc
              special=vmi-perf
Annotations:  k8s.v1.cni.cncf.io/networks: sriov-net1
              kubevirt.io/latest-observed-api-version: v1
              kubevirt.io/storage-observed-api-version: v1alpha3
API Version:  kubevirt.io/v1
Kind:         VirtualMachineInstance
Metadata:
  Creation Timestamp:  2021-10-18T09:35:20Z
  Finalizers:
    foregroundDeleteVirtualMachine
  Generation:  9
  Managed Fields:
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .:
          f:k8s.v1.cni.cncf.io/networks:
          f:kubectl.kubernetes.io/last-applied-configuration:
        f:labels:
          .:
          f:special:
      f:spec:
        .:
        f:domain:
          .:
          f:cpu:
            .:
            f:cores:
            f:dedicatedCpuPlacement:
            f:model:
            f:sockets:
            f:threads:
          f:devices:
            .:
            f:disks:
            f:interfaces:
            f:rng:
          f:machine:
            .:
            f:type:
          f:resources:
            .:
            f:limits:
              .:
              f:intel.com/intel_sriov_netdevice:
              f:memory:
            f:requests:
              .:
              f:intel.com/intel_sriov_netdevice:
              f:memory:
        f:networks:
        f:terminationGracePeriodSeconds:
        f:volumes:
    Manager:      kubectl
    Operation:    Update
    Time:         2021-10-18T09:35:20Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:kubevirt.io/latest-observed-api-version:
          f:kubevirt.io/storage-observed-api-version:
        f:labels:
          f:kubevirt.io/nodeName:
      f:status:
        f:activePods:
          .:
          f:34862f44-deea-4ef3-b60e-66fe61c1dc98:
        f:nodeName:
        f:phase:
        f:qosClass:
    Manager:      virt-controller
    Operation:    Update
    Time:         2021-10-18T09:36:33Z
    API Version:  kubevirt.io/v1alpha3
    Fields Type:  FieldsV1
    fieldsV1:
      f:status:
        f:conditions:
        f:interfaces:
        f:migrationMethod:
    Manager:         virt-handler
    Operation:       Update
    Time:            2021-10-18T09:36:35Z
  Resource Version:  1505373
  Self Link:         /apis/kubevirt.io/v1/namespaces/default/virtualmachineinstances/vmi-perf
  UID:               fe5a166c-7d8c-4064-b1e1-d90eb3a07875
Spec:
  Domain:
    Cpu:
      Cores:                    1
      Dedicated Cpu Placement:  true
      Model:                    host-passthrough
      Sockets:                  2
      Threads:                  1
    Devices:
      Disks:
        Disk:
          Bus:  virtio
        Name:   containerdisk
        Disk:
          Bus:  virtio
        Name:   cloudinitdisk
      Interfaces:
        Masquerade:
        Name:  default
        Name:  sriov-net1
        Sriov:
      Rng:
    Features:
      Acpi:
        Enabled:  true
    Firmware:
      Uuid:  3d51af79-949f-4286-b6e7-8a2f12fd663f
    Machine:
      Type:  q35
    Resources:
      Limits:
        intel.com/intel_sriov_netdevice:  1
        Memory:                           4Gi
      Requests:
        intel.com/intel_sriov_netdevice:  1
        Memory:                           4Gi
  Networks:
    Name:  default
    Pod:
    Multus:
      Network Name:                  default/sriov-net1
    Name:                            sriov-net1
  Termination Grace Period Seconds:  0
  Volumes:
    Container Disk:
      Image:              docker.io/kubevirt/fedora-cloud-container-disk-demo:latest
      Image Pull Policy:  Never
    Name:                 containerdisk
    Cloud Init No Cloud:
      User Data:  #!/bin/bash
echo "centos" |passwd centos --stdin
dhclient eth1

    Name:  cloudinitdisk
Status:
  Active Pods:
    34862f44-deea-4ef3-b60e-66fe61c1dc98:  uos-pc
  Conditions:
    Last Probe Time:       <nil>
    Last Transition Time:  <nil>
    Status:                True
    Type:                  LiveMigratable
    Last Probe Time:       <nil>
    Last Transition Time:  2021-10-18T09:36:35Z
    Message:               server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: host doesn't support passthrough of host PCI devices')"
    Reason:                Synchronizing with the Domain failed.
    Status:                False
    Type:                  Synchronized
  Guest OS Info:
  Interfaces:
    Ip Address:  192.168.0.51
    Ip Addresses:
      192.168.0.51
    Mac:             52:54:00:7b:85:e1
    Name:            default
  Migration Method:  BlockMigration
  Node Name:         uos-pc
  Phase:             Scheduled
  Qos Class:         Guaranteed
Events:
  Type     Reason            Age                 From                       Message
  ----     ------            ----                ----                       -------
  Normal   SuccessfulCreate  96s                 virtualmachine-controller  Created virtual machine pod virt-launcher-vmi-perf-pr5r2
  Warning  SyncFailed        10s (x13 over 21s)  virt-handler, uos-pc       server error. command SyncVMI failed: "LibvirtError(Code=67, Domain=10, Message='unsupported configuration: host doesn't support passthrough of host PCI devices')"

**Comment by adrianchiris** [comment]
Are you able to create a Pod with SRIOV resource ?

**Comment by newhuangchuan** [comment]
Hello, it is possible to create a pod.

```
uos@uos-PC:~/kubevirt/network$ kubectl  get pod  && kubectl get vmi
NAME                           READY   STATUS    RESTARTS   AGE
testpod1                       1/1     Running   3          163m
testpod2                       1/1     Running   3          162m
```
The yaml configuration is as follows:
```
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net1
spec:
  containers:
  - name: appcntr1 
    image: centos/tools 
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        intel.com/intel_sriov_netdevice: '1'
      limits:
        intel.com/intel_sriov_netdevice: '1'
```
