### ISSUE TITLE
Cannot ping sriov in pod if they are on different Nodes

### ISSUE THREAD

**Issue by lzd-1230** [k8snetworkplumbingwg/sriov-network-device-plugin#535]
Hi guys I got trouble in using sriov-plugin along with multus-cni in pod. Problem is same as this [issue](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/204).
**Which is 2 pod on 2 difference node cannot ping each other. However, when they are on the same host, they can ping each other successfully**

I'm using ConnectX-3 Pro Interface in all hosts in k8s, and it work well when not in pod in 192.168.2.0/24.

![image](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/assets/68856054/f6e25564-469c-4047-b002-d1aa1931ede0)

here is my `ip link` output in host in first host(They got a lot of fake name because of my few times try).

![image](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/assets/68856054/b6191204-4fea-4c1a-94bd-cc0b5244241f)

This is my configmap  of sriovdp-config

```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: sriovdp-config
  namespace: kube-system
data:
  config.json: |
    {
        "resourceList": [
            {
                "resourcePrefix": "mellanox",
                "resourceName": "flr544",
                "selectors":
                {
                    "vendors": ["15b3"],
                    "devices": ["1004"],
                    "drivers": ["mlx4_core"]
                }
            }
        ]
    }
```
and I create a NetworkAttachmentDefinition as follows:
```yaml
apiVersion: "k8s.cni.cncf.io/v1"
kind: NetworkAttachmentDefinition
metadata:
  name: sriov-net
  annotations:
    k8s.v1.cni.cncf.io/resourceName: mellanox/flr544
spec:
  config: '{
    "type": "sriov",
    "cniVersion": "0.3.1",
    "name": "sriov-net",
    "ipam": {
      "type": "whereabouts",
      "datastore": "k8s",
      "range": "192.168.3.0/24",
      "gateway": "192.168.3.1",
      "routes": [{
        "dst": "192.168.0.0/24",
        "gw": "192.168.3.1"
      }]
    }
  }'
```
Last, I create testpod and they can all get the `net1` interface deliverd by `sriov-net` successfully, and when I schedule the pod to same server, it can work very well! And I found arp is working well.
```shell
[root@testpod1 /]# ip neigh
192.168.3.1 dev net1 lladdr a2:f2:ba:ca:fc:a0 REACHABLE
```

But wired thing is after changing the schedule to different host, it failed.

The testpod yaml is here: 
```yaml
apiVersion: v1
kind: Pod
metadata:
  name: testpod1
  annotations:
    k8s.v1.cni.cncf.io/networks: sriov-net
spec:
  containers:
  - name: appcntr1
    image: centos/tools
    imagePullPolicy: IfNotPresent
    command: [ "/bin/bash", "-c", "--" ]
    args: [ "while true; do sleep 300000; done;" ]
    resources:
      requests:
        mellanox/flr544: '1'
      limits:
        mellanox/flr544: '1'
  nodeSelector:
    kubernetes.io/hostname: pve1.myslab.site 
```
After changing `nodeSelector` to different nodes which all get net1 with 192.168.3.1 and 192.168.3.2, they failed to ping.

Here's the details:
```
 kubectl get pod -n code-server -o wide -w                                              root@pve1
NAME       READY   STATUS    RESTARTS   AGE   IP             NODE               NOMINATED NODE   READINESS GATES
testpod1   1/1     Running   0          26s   172.20.0.21    pve2.myslab.site   <none>           <none>
testpod2   1/1     Running   0          12m   172.20.2.127   pve1.myslab.site   <none>           <none>

# ip addr in testpod1
[root@testpod1 /]# ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
10: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether 12:f4:11:00:3e:cf brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.2/24 brd 192.168.3.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::10f4:11ff:fe00:3ecf/64 scope link
       valid_lft forever preferred_lft forever
70: eth0@if71: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether 12:eb:04:40:aa:28 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.0.21/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::10eb:4ff:fe40:aa28/64 scope link
       valid_lft forever preferred_lft forever

# ip addr in pod2
[root@testpod2 /]# ip ad
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1000
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host
       valid_lft forever preferred_lft forever
27: net1: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc mq state UP group default qlen 1000
    link/ether a2:f2:ba:ca:fc:a0 brd ff:ff:ff:ff:ff:ff
    inet 192.168.3.1/24 brd 192.168.3.255 scope global net1
       valid_lft forever preferred_lft forever
    inet6 fe80::a0f2:baff:feca:fca0/64 scope link
       valid_lft forever preferred_lft forever
180: eth0@if181: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc noqueue state UP group default qlen 1000
    link/ether b6:6a:59:1f:09:98 brd ff:ff:ff:ff:ff:ff link-netnsid 0
    inet 172.20.2.127/32 scope global eth0
       valid_lft forever preferred_lft forever
    inet6 fe80::b46a:59ff:fe1f:998/64 scope link
       valid_lft forever preferred_lft forever
```

They can only ping themselves each, and cannot to each other.

![image](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/assets/68856054/b4ee2645-693b-40be-9861-b1550ef4a533)

I watch some issues and got some question

[issue](https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/issues/204#issuecomment-585863958):  I checked my ip link and it got all 00:00:00:00 after the sriov is given to pod, am I miss some pre-configureation for sriov in host?

Please feel free to give me some guidance!
