### ISSUE TITLE
grpc server: better to implement GetPreferredAllocation function

### ISSUE THREAD

**Issue by cyclinder** [k8snetworkplumbingwg/sriov-network-device-plugin#574]
## What would you like to be added?

If pod declares both gpu and sriov resources, as follows:

```
        resources:
          limits:
            nvidia.com/gpu: 1
            spidernet.io/sriov_net_device: 1
```

I hope that the topology of the assigned vf and gpu is at least PHB(or PXB, PIX), so that the communication between them can enable GPU Direct RDMA, greatly improving the communication speed between them.

![image](https://github.com/user-attachments/assets/d865bdcc-5c83-47a1-a298-b79dba5d4e0f)

NOTE:  I think the Gpu-device-plugin should also implement this function, because we don't know who will allocate the GPU or VF first.

see https://github.com/k8snetworkplumbingwg/sriov-network-device-plugin/blob/60208ae3957ded8d8a4125fd8758e1f479822ea0/pkg/resources/server.go#L224
